<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wifi" nsURI="http://www.example.org/wifi" nsPrefix="wifi">
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSocket">
    <eOperations name="hasName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RemoteType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="houseCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiverCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RemoteType">
    <eLiterals name="HouseCodeSocket" literal="ATypeSocketA"/>
    <eLiterals name="AddressCodeSocket" value="1" literal="BTypeSocket"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SocketGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Members" upperBound="-1"
        eType="#//RemoteSocket" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSockets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SocketGroups" upperBound="-1"
        eType="#//SocketGroup" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
